### PR TITLE
Add setup.py, make pip installable

### PR DESCRIPTION
**Pull request by ctb**
Hello! Thank you for vamb!

This PR makes a few changes to make vamb pip installable, which is necessary (or at least a good idea :) for building a bioconda package and/or making vamb available via PyPI (e.g. https://pypi.org/project/vamb/). For developers, it also means you can run 'pip install -e .' to run vamb in developer mode, so as to avoid mucking around with paths etc. etc.

Briefly, I did the following:

- removed `.so` and `__pycache__` files from repository as platform specific and/or generated;
- created a `vamb` package directory;
- moved `run.py` to __main__.py and encapsulated the top level commands in a function that can be used as a setuptools entrypoint;
- created a `setup.py` with a version string and setuptools commands to build the Cython extension from scratch;

This changes the install & run instructions, too. There are a few new ways to install & run vamb from this branch:

## Installing

(requires pytorch and pysam installs; see [my draft quickstart guide](https://hackmd.io/mpWlv3jeR3uoYCIh4h-7sQ?both) for those commands.)

### Install #1 - user mode

This is for users who don't want to edit or view the source code:
```
pip install Cython
pip install -U https://github.com/ctb/vamb/archive/add_setup.zip
```

### Install #2 - developer mode

This is for developers who want to be able to edit Python files and have the changes show up directly in the running command:

```
# clone repo
git clone https://github.com/ctb/vamb -b add_setup

# dev install
cd vamb
pip install -e .
```

Note that any changes you make to the .pyx file requires that you run `python setup.py build_ext -i` to update the compiled files.

## Running

You can now do either
```
python -m vamb
```
or just straight up
```
vamb
```
-- the former is nice because you can nail down the version of Python you want to run, whereas the latter is nice for users who don't care that it's written in Python!

Note that vamb is also importable as you'd expect: `import vamb`.

### CODE REVIEW

**Comment by jakobnissen** [comment]
Oh, very nice! I never added the `setup.py` because I don't understand how it works. But it would indeed be useful to be able to download Vamb directly from pip. Perhaps even better, with your setup script, the binaries will automatically be created on installation. Those have been causing me some headache.

Your `__main__.py` script doesn't work, at least when I test it with a small dataset. The issue seems to be that since vamb is not imported in the file, nowhere in the file is the name `vamb` defined - in other words, while the `__main__.py` script executes `__init__.py` and therefore imports vamb, it can't access it. I still don't understand how `__main.py__` and `__init__.py` interact, so I can't help you there.

One more thing - can I ask you to rebase your PR on the `dev` branch? The `parsebam.py` file is different (this should not cause any issues), but so is `run.py`. On the `dev` branch, numpy is imported after the requested number of processors have been parsed, such that the number of threads can be set beforehand.

**Comment by ctb** [comment]
Yep! Will fix :)

--
Titus Brown, ctbrown@ucdavis.edu<mailto:ctbrown@ucdavis.edu>

On Dec 30, 2018, at 9:35 AM, Jakob Nybo Nissen <notifications@github.com<mailto:notifications@github.com>> wrote:


Oh, very nice! I never added the setup.py because I don't understand how it works. But it would indeed be useful to be able to download Vamb directly from pip. Perhaps even better, with your setup script, the binaries will automatically be created on installation. Those have been causing me some headache.

Your __main__.py script doesn't work, at least when I test it with a small dataset. The issue seems to be that since vamb is not imported in the file, nowhere in the file is the name vamb defined - in other words, while the __main__.py script executes __init__.py and therefore imports vamb, it can't access it. I still don't understand how __main.py__ and __init__.py interact, so I can't help you there.

One more thing - can I ask you to rebase your PR on the dev branch? The parsebam.py file is different (this should not cause any issues), but so is run.py. On the dev branch, numpy is imported after the requested number of processors have been parsed, such that the number of threads can be set beforehand.

**Comment by ctb** [comment]
hi @jakobnissen give this one a try.

what's the right way to run some test commands so I can verify this for myself?

**Comment by ctb** [comment]
I took a look through the tutorial ipynb, and it looks like all I would need are `example/contigs.fna` and a few of the `bamfiles/e101.filtered.bam`. Are these available for download anywhere? I'll keep on digging as I have time but thought you might have a quick answer :)

**Comment by jakobnissen** [comment]
@ctb 
Thank you for this contribution. I'll merge this and if there's any bugs or kinks in the code, I'll work them out myself.
For testing, you basically just run the `test/runtests.py` scripts, and if no errors are raised, it works. The test suite is rather basic though, and does not for example test whether there are bugs in the arg parser. So before merging into master branch, I'll also run the entire pipeline to make sure it works.
Regarding the data files for the notebook, I can't share those files. Also, I wouldn't bet on Vamb working well with very small amounts of data (e.g. hundreds of sequences) where it could easily overfit, so it's not ideal to distribute the test files. Perhaps there are some sites where I could upload a multi-gigabyte data archive for people to test run Vamb on.

**Comment by ctb** [comment]
excellent! I am happy to help, feel free to tag me in to a PR or issue if
you have some obscure Python problem.

I use osf.io for up to 5 GB. Happy to help with that as well :)

**Pull request merged**
